image: node:8.10

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy
  - e2e
  - approvals
  - production

before_script:

tests all:
  stage: test
  script:
    - npm install
    - npm test
  environment: test

codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate 
    - docker run -v /tmp/cc:/tmp/cc -v "$PWD":/code -v /var/run/docker.sock:/var/run/docker.sock codeclimate/codeclimate validate-config
    - ls -lash $PWD
    - echo $PWD
    - docker run --env CODECLIMATE_CODE="$PWD" -v "$PWD":/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > gl-code-quality-report.json
  environment: dev
  artifacts:
    paths: [gl-code-quality-report.json]

approval:
  stage: approvals
  script:
    - echo "aprovado deploy para producao"
  allow_failure: false
  environment: prod
  when: manual
